### ISSUE TITLE
Install problem : In ArrayLoader.php line 44:

### ISSUE THREAD

**Issue by gamersalpha** [secit-pl/imap-bundle#10]
Hello i got a problem when i try to install it :  

i install symfony : 

>```
 symfony new my_project

>  composer require secit-pl/imap-bundle

In ArrayLoader.php line 44:

Unknown package has no name defined ([{"name":"psr\/cache","version":"1.0.1","version_normalized":"1.0.1.0","source":{"type":"git","url":"https:\/\/github.com\/php-fig\/cache.git","reference":"d11b50ad223250cf17b86e38383413f5a6764bf
  8"},"dist":{"type":"zip","url":"https:\/\/api.github.com\/repos\/php-fig\/cache\/zipball\/d11b50ad223250cf17b86e38383413f5a6764bf8","reference":"d11b50ad223250cf17b86e38383413f5a6764bf8","shasum":""},"require":{"php":">=5.3.0"},"tim
  e":"2016-08-06T20:24:11+00:00","type":"library","extra":{"branch-alias":{"dev-master":"1.0.x-dev"}},"installation-source":"dist","autoload":{"psr-4":{"Psr\\Cache\\":"src\/"}},"notification-url":"https:\/\/packagist.org\/downloads\/"
  ,"license":["MIT"],"authors":[{"name":"PHP-FIG","homepage":"http:\/\/www.php-fig.org\/"}],"description":"Common interface for caching libraries","keywords":["cache","psr","psr-6"],"support":{"source":"https:\/\/github.com\/php-fig\/
  cache\/tree\/master"},"install-path":"..\/psr\/cache"},{"name":"psr\/container","version":"1.1.1","version_normalized":"1.1.1.0","source":{"type":"git","url":"https:\/\/github.com\/php-fig\/container.git","reference":"86225674090102
  82b7aeebe4bb841fe98b58dcaf"},"dist":{"type":"zip","url":"https:\/\/api.github.com\/repos\/php-fig\/container\/zipball\/8622567409010282b7aeebe4bb841fe98b58dcaf","reference":"8622567409010282b7aeebe4bb841fe98b58dcaf","shasum":""},"re
  quire":{"php":">=7.2.0"},"time":"2021-03-05T17:36:06+00:00","type":"library","installation-source":"dist","autoload":{"psr-4":{"Psr\\Container\\":"src\/"}},"notification-url":"https:\/\/packagist.org\/downloads\/","license":["MIT"],
  "authors":[{"name":"PHP-FIG","homepage":"https:\/\/www.php-fig.org\/"}],"description":"Common Container Interface (PHP FIG PSR-11)","homepage":"https:\/\/github.com\/php-fig\/container","keywords":["PSR-11","container","container-in
  terface","container-interop","psr"],"support":{"issues":"https:\/\/github.com\/php-fig\/container\/issues","source":"https:\/\/github.com\/php-fig\/container\/tree\/1.1.1"},"install-path":"..\/psr\/container"},{"name":"psr\/event-di
  spatcher","version":"1.0.0","version_normalized":"1.0.0.0","source":{"type":"git","url":"https:\/\/github.com\/php-fig\/event-dispatcher.git","reference":"dbefd12671e8a14ec7f180cab83036ed26714bb0"},"dist":{"type":"zip","url":"https:
  \/\/api.github.com\/repos\/php-fig\/event-dispatcher\/zipball\/dbefd12671e8a14ec7f180cab83036ed26714bb0","reference":"dbefd12671e8a14ec7f180cab83036ed26714bb0","shasum":""},"require":{"php":">=7.2.0"},"time":"2019-01-08T18:20:26+00:
  00","type":"library","extra":{"branch-alias":{"dev-master":"1.0.x-dev"}},"installation-source":"dist","autoload":{"psr-4":{"Psr\\EventDispatcher\\":"src\/"}},"notification-url":"https:\/\/packagist.org\/downloads\/","license":["MIT"
  ],"authors":[{"name":"PHP-FIG","homepage":"http:\/\/www.php-fig.org\/"}],"description":"Standard interfaces for event handling.","keywords":["events","psr","psr-14"],"support":{"issues":"https:\/\/github.com\/php-fig\/event-dispatch
  er\/issues","source":"https:\/\/github.com\/p ....

```

what is wrong please ??

**Comment by secit-pl** [comment]
Try this https://craftcms.stackexchange.com/questions/36551/unknown-package-has-no-name-defined-composer-error-on-upgrade
