### ISSUE TITLE
Attachment folder permissions

### ISSUE THREAD

**Issue by bcaly** [secit-pl/imap-bundle#12]
Hi !

If I choose to put my attachments in the folder "myproject/var/tmp" and it doesn't exist, it will create with the permissions 0770, but if I use another bundle to generate PDF (for exemple) and I choose this same folder, I have an error : Warning: copy(/var/www/var/tmp/filename.pdf): failed to open stream: Permission denied.

Could you change the permissions by 0777 to create the folder ?

Thanks !

**Comment by secit-pl** [comment]
Hi.

Move to version >=1.5 and `created_attachments_dir_permissions` parameter is what you need.
