### ISSUE TITLE
Attempted to call an undefined method named "testConnection" of class "PhpImap\Mailbox".

### ISSUE THREAD

**Issue by gamersalpha** [secit-pl/imap-bundle#14]
Hello, 

i got this error how fix please :

  public function indexAction(Imap $imap)
    {
        $exampleConnection = $imap->get('example_connection');

// testing with a full error message
try {
    $isConnectable = $imap->get('example_connection')->testConnection('example_connection', true);
} catch (\Exception $exception) {
    echo $exception->getMessage();
}

**Comment by secit-pl** [comment]
Make sure that you are using the latest version of this bundle and your cache was cleared.
