### ISSUE TITLE
Allow symfony 6

### ISSUE THREAD

**Issue by ehymel** [secit-pl/imap-bundle#16]
Can you tag your most recent changes to allow symfony 6 integration? Thanks!

**Comment by EpicKau** [comment]
please @p-w @phansys @secit-pl @DaDeather

**Comment by DaDeather** [comment]
@EpicKau @ehymel 

I have created an own bundle based of this one which will be maintained more activly. You can use that one for Symfony 4.*, 5.* and 6.*

See: https://github.com/DaDeather/symfony-imap-bundle

**Comment by ehymel** [comment]
@DaDeather Thank you!

**Comment by secit-pl** [comment]
Version 1.5 released.

**Comment by Chris53897** [comment]
@DaDeather Can you create a PR for your changes? I think it is in most cases better to have one leading main repo.
Update: I just saw you created a new Repo instead of a fork. That of course it not the normal way and makes PR much harder.
