### ISSUE TITLE
directory permissions wrong? 

### ISSUE THREAD

**Issue by akmez** [secit-pl/imap-bundle#18]
created_attachments_dir_permissions is declared as an integer node in configuration https://github.com/secit-pl/imap-bundle/blob/master/DependencyInjection/Configuration.php#L53 

When default value is 770 , the variable $directoryPermissions in https://github.com/secit-pl/imap-bundle/blob/master/Service/Imap.php#L119 has the integer value 770. And when we decoct(770) we have "1402" as permissions  and  creating the folder with wrong permissions. 

Why dont pass the created_attachments_dir_permissions as scalarNode ?  

php version 7.2.24 
secit-pl/imap-bundle version 1.5.0

**Comment by secit-pl** [comment]
Should be octdec not decoct, sorry. Fixed in version 1.5.1.
