### ISSUE TITLE
Problems in my Docker Environment

### ISSUE THREAD

**Issue by tomwuell** [secit-pl/imap-bundle#19]
Hey, 
after installing it on my Symfony Docker environment I get the following Error:

Attempted to call function "imap_search" from namespace "PhpImap"

What can I do to solve this?

**Comment by marc-schumann** [comment]
you need to install php imap extension within docker. maybe you need to add it to the namespace via composer as well.

**Comment by Chris53897** [comment]
I am wondering why you can install it with composer if you do not have the extension.
PHP-IMAP has `ext-imap: *` in the require-section.
https://packagist.org/packages/php-imap/php-imap#5.0.0

**Comment by secit-pl** [comment]
@Chris53897 --ignore-platform-reqs 

@tomwuell as they said check that you have installed php imap extension.
