### ISSUE TITLE
Minor symfony 6.1 deprecation

### ISSUE THREAD

**Issue by ehymel** [secit-pl/imap-bundle#20]
After upgrading to symfony 6.1, I'm getting this new deprecation:

`Method "Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()" might add "TreeBuilder" as a native return type declaration in the future. Do the same in implementation "SecIT\ImapBundle\DependencyInjection\Configuration" now to avoid errors or add an explicit @return annotation to suppress this message.`

Seems like an easy fix...

**Comment by secit-pl** [comment]
Fixed by https://github.com/secit-pl/imap-bundle/pull/21
