### ISSUE TITLE
New Major version with PHP >= 8.0 and Symfony >= 5.4

### ISSUE THREAD

**Issue by Chris53897** [secit-pl/imap-bundle#23]
@secit-pl 
Are you open for a PR for a new major version with PHP >= 8.0 and Symfony >= 5.4, strong types and new language level features?
Composer handles the old version, so there is no problem with existing users of this repo.

I can start the PR after I have your go.

**Comment by secit-pl** [comment]
If you could take care of this I'd love to merge such change :)

This will break a lot of backward compatibility so I think it should be released as version 2.0.0.

**Comment by secit-pl** [comment]
Hi. Merged and will be released (v2.0.0) probably today.
