### ISSUE TITLE
oAuth authentication support

### ISSUE THREAD

**Issue by pbories** [secit-pl/imap-bundle#28]
Hello @secit-pl, 

I installed imap-bundle on my Symfony 5.4 project, but cannot authenticate on Office 365 to retrieve emails with IMAP.

The reason is probably the deprecation of basic authentication by Microsoft :
https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online?source=recommendations

Is there a way to use an oAuth access token to authenticate ? If not, is it going to be supported in the future ?

Thanks you !

**Comment by Chris53897** [comment]
You probably want to add your issue here https://github.com/barbushin/php-imap
And close this one.

This repo is just a wrapper for php-imap

**Comment by secit-pl** [comment]
That's right. Closing.
