### ISSUE TITLE
Undefined constant 'OP_READONLY'

### ISSUE THREAD

**Issue by dschiffel** [secit-pl/imap-bundle#29]
Hi!
After migration to new server with PHP 8.0 I get this error in 
vendor/secit-pl/imap-bundle/Service/Imap.php:97

Symfony 5.3.9 

Can anybody advice me?

**Comment by secit-pl** [comment]
Which bundle version are you using?

**Comment by secit-pl** [comment]
I guess you are using the version 1.x, please try swtich to version 2 and see it if it helps.

**Comment by secit-pl** [comment]
Closing due to no response.
