### ISSUE TITLE
Delete mailbox is not working

### ISSUE THREAD

**Issue by tintusumith** [secit-pl/imap-bundle#3]
1.Hi, When I am trying to delete a mailbox that created manually in my account(ex: test), some error showing. I think its due to one extra '.' appended between mailbox path and mailbox name.
Please refer the code given below.
public function deleteMailbox($name) {
		$this->imap('deletemailbox', $this->imapPath . '.' . $name);
}
2.When I create a mailbox using createMailbox($name), one extra '.' appended before the mailbox name. This issue exists in rename function also

**Comment by secit-pl** [comment]
Hi,

the problem you described is not in the [secit-pl/imap-bundle](https://github.com/secit-pl/imap-bundle) but in the package [php-imap/php-imap](https://github.com/barbushin/php-imap) which this bundle wraps.

Please report it on their issues page: https://github.com/barbushin/php-imap/issues.
