### ISSUE TITLE
Undefined constant 'OP_READONLY'

### ISSUE THREAD

**Issue by V-Ostrovski** [secit-pl/imap-bundle#30]
Hello.

I got this exeption in php 7.3 and symfony 2.8.52.
How to fix this?

**Comment by garbast** [comment]
Just define a const OP_READONLY with the value 2 should do the trick.

see https://github.com/barbushin/php-imap/blob/9857a1dc4c9c5f37c51ba2a63ce7cc2da9cab41b/src/PhpImap/Mailbox.php

**Comment by davidriveracoro** [comment]
Could you solve the problem? I don't know in what part must I define const OP_READONLY with the value 2

**Comment by secit-pl** [comment]
OP_READONLY is constant from PHP imap extension. You do not have imap extension enabled.

https://www.php.net/manual/en/imap.constants.php
