### ISSUE TITLE
Automatically create attachments directory

### ISSUE THREAD

**Issue by ocjojo** [secit-pl/imap-bundle#4]
I have a config containing
```yaml
attachments_dir: "%kernel.project_dir%/var/imap/attachments"
```
This leads to the following error:
```
ERROR     [app] Directory "/application/var/imap/attachments" not found [] []
```
In my opinion the bundle should try to create the directory, if it does not exist.
Or is there a reason it is just giving an error?

**Comment by secit-pl** [comment]
I agree that the bundle should create a directory if it not exists.

Added in release 1.3.1
