### ISSUE TITLE
attachment support 

### ISSUE THREAD

**Issue by grekpg** [secit-pl/imap-bundle#5]
i see my attachment

IncomingMailAttachment {#563 ▼
+id: "14221071831878934793"
+contentId: "auto_cid_2817556830"
+name: "cpanel-logo-tiny.png"
+filePath: null
+disposition: "attachment"
}

how i can download it ?

**Comment by sergiotropea** [comment]
i have the same question...

**Comment by secit-pl** [comment]
The question you asked is not directly related to this bundle, it should be asked here:
https://github.com/barbushin/php-imap

This bundle only wraps PHP-IMAP to allow easy Symfony integration.
